global:
  scrape_interval: 1m

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: mqtt
    static_configs:
      - targets: ["mosquitto-exporter:9234"]

  - job_name: fluentd
    scrape_interval: 5s
    static_configs:
    - targets:
      - fluentd:8000